# Generated by Django 5.1.3 on 2024-11-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_rename_price_house_pricepernight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='pricePerNight',
            new_name='price_per_night',
        ),
        migrations.AddField(
            model_name='house',
            name='pet_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
