# Generated by Django 5.1.3 on 2024-11-27 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='payroad',
            new_name='payload',
        ),
    ]
