# Generated by Django 5.1.3 on 2024-11-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='owner',
            new_name='user',
        ),
    ]
